### ISSUE TITLE
release fails if gh-pages branch doesn't yet exist

### ISSUE THREAD

**Issue by paulczar** [helm/chart-releaser-action#10]
the `cr.sh` script creates the worktree for gh-pages branch fails when the `gh-pages` doesn't yet exist. 

We should add some logic to check if it exists, and if not, add it, rather than fail

https://github.com/helm/chart-releaser-action/blob/master/cr.sh#L217

**Comment by chrissng** [comment]
In the meanwhile one could add this step in GH action for pull request (e.g. linting your chart):
```yaml
      - name: Check for gh-pages branch
        run: |
          git ls-remote --exit-code --heads origin gh-pages
```

**Comment by invidian** [comment]
>In the meanwhile one could add this step in GH action for pull request (e.g. linting your chart):

I'm not sure how this helps, it just shifts the failure from later stage to early. It would be nice to have documented how to create this branch.

**Comment by thetredev** [comment]
My workaround:
```yaml
- name: Configure Git
  run: |
    git config user.name "$GITHUB_ACTOR"
    git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

# maybe fixes the release ...
- name: Prepare gh-pages branch
  run: |
    git branch gh-pages || true
    git checkout gh-pages
    git rebase main
    git push origin gh-pages -f

    git checkout main

- name: Run chart-releaser
  uses: helm/chart-releaser-action@v1.5.0
  env:
    CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But I think this is very ugly... I'll probably do my own thing instead. This action is not what I expected tbh..
