### ISSUE TITLE
Target a specific chart to release

### ISSUE THREAD

**Issue by juadk** [helm/chart-releaser-action#100]
First, I didn't find similar issue either in the repo or in internet.
I'd like to release only one chart inside my chart folder.
Let's say:
```
my_project/
  chart/
    chart1/
    chart2/
```
In my github action, I use:
```
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: chart/chart2
```
But chart-releaser is still checking the whole chart dir, am I missing something?
