### ISSUE TITLE
feat: add support for pushing charts to oci (ghcr)

### ISSUE THREAD

**Issue by dmccaffery** [helm/chart-releaser-action#107]
Add support for pushing charts to GHCR in addition to releases.

As of [helm v3.8.0](https://github.com/helm/helm/releases/tag/v3.8.0), oci support is now generally available.

Dependency: https://github.com/helm/chart-releaser/issues/183

**Comment by acuD1** [comment]
This PR (#143) should solve this issue. Just need to add `--skip-upload`.

There is a snippet from my CI workflow:

```yaml
      - name: Run chart-releaser
        uses: acuD1/chart-releaser-action@main
        with:
          skip_upload: true
        env:
          CR_TOKEN: "${{ secrets.CI_TOKEN }}"

      - name: Login to GHCR
        uses: acuD1/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_TOKEN }}
          
      - name: Push Charts to GHCR
        run: |
          for pkg in .cr-release-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" oci://ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY }}
          done
```

Until it's fully released (https://github.com/helm/chart-releaser-action/issues/186) you can use my branch.
