### ISSUE TITLE
Missing permission in README example

### ISSUE THREAD

**Issue by stkr22** [helm/chart-releaser-action#110]
In the README.md it shows an example workflow:

```yaml
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

At least for me that did not work. The task always terminated with " 403 Resource not accessible by integration". Once I added the necessary permissions it worked:

```yaml
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest

[....]
```
