### ISSUE TITLE
Error: could not find : no matching version

### ISSUE THREAD

**Issue by dcoraboeuf** [helm/chart-releaser-action#128]
Hi,

I've been using `chart-releaser-action` for quite some time in the https://github.com/nemerosa/ontrack-chart workflow.

But now, today, after having committed a change and changed the `version` and `appVersion` values, the action systematically fails with the following message:

```
Looking up latest tag...
Discovering changed charts since 'ontrack-0.7.7'...
Installing chart-releaser on /opt/hostedtoolcache/cr/v1.5.0/x86_64...
Adding cr directory to PATH...
Packaging chart 'charts/ontrack'...
Error: could not find : no matching version
```

The workflow is very basic:

```

name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Helm dependencies repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add elastic https://helm.elastic.co
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

Since the workflow is public, I put the link to the action log, just in case this may help solving this issue: https://github.com/nemerosa/ontrack-chart/actions/runs/3981029467/jobs/6824490383

Thanks for any hint in resolving this issue,
Damien
