### ISSUE TITLE
README example uses v1.6.0 but that doesn't exist

### ISSUE THREAD

**Issue by remram44** [helm/chart-releaser-action#152]
```yaml
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

Latest tag is v1.5.0
