### ISSUE TITLE
Nothing to do. No chart changes detected.

### ISSUE THREAD

**Issue by darox** [helm/chart-releaser-action#179]
I have a workflow of:
```
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: './lobe-chat'
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

But the run always returns:
```
Run helm/chart-releaser-action@v1.6.0
Run owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
Looking up latest tag...
Discovering changed charts since '7ac38b386b8[9](https://github.com/darox/helm-charts/actions/runs/7259817070/job/19777701605#step:5:10)385[70](https://github.com/darox/helm-charts/actions/runs/7259817070/job/19777701605#step:5:72)f5242ac141f829f20221409'...
Nothing to do. No chart changes detected.
```

The hash linked corresponds to:
https://github.com/darox/helm-charts/commit/7ac38b386b8938570f5242ac141f829f20221409

And since then many commits were added. 

Still, the action doesn't release a new chart version. 

What's the deal here?
