### ISSUE TITLE
skip_upload flag is not in the latest release

### ISSUE THREAD

**Issue by rochana-atapattu** [helm/chart-releaser-action#191]
```
- name: Run chart-releaser
   uses: helm/chart-releaser-action@v1.6.0
    with:
      skip_upload: true
```
getting following error

> Unexpected input(s) 'skip_upload', valid inputs are ['version', 'config', 'charts_dir', 'install_dir', 'install_only', 'skip_packaging', 'skip_existing', 'mark_as_latest', 'packages_with_index', 'pages_branch']

 look like following code is not in the latest release even though its in the docs and main branch
https://github.com/helm/chart-releaser-action/blame/0eba7f523fccbf0577905877226d6c576fc2de61/action.yml#L46
