### ISSUE TITLE
Only package charts when the chart version has changed

### ISSUE THREAD

**Issue by AndersBennedsgaard** [helm/chart-releaser-action#209]
We need to do some preprocessing which runs dereferencing on the JSON schema we use for our Helm chart values, before packaging our charts. That means the `git diff` command in this action always detects changes:

https://github.com/helm/chart-releaser-action/blob/d1e09fd16821c091b45aa754f65bae4dd675d425/cr.sh#L297

In my mind, it would make sense for `cr` to only package and release charts where the version has been bumped - at the least optionally, using a flag such as `only_package_on_version_change` (naming is hard..)

Currently we run the packaging step ourselves, and only detect charts that have changed their version:

```bash
source_sha="${{ github.event.pull_request.base.sha }}" # base commit in the PR
target_sha="${{ github.sha }}" # merge commit sha
# get the list of charts that have changed
changed="$(git diff --name-only --diff-filter=ACMRT "$source_sha" "$target_sha" -- "charts/*/Chart.yaml" | cut -d '/' -f 2)"

# check if the PR has modified any chart versions
# prevent https://www.shellcheck.net/wiki/SC2030 using '<<<' to read into an array
changed_charts=()
while read -r chart; do
  old_version="$(git show "$source_sha":"charts/$chart/Chart.yaml" | yq '.version')"
  new_version="$(yq '.version' "charts/$chart/Chart.yaml")"
  if [[ "$old_version" != "$new_version" ]]; then
    echo "::notice::Chart '$chart' has changed from version $old_version to $new_version"
    changed_charts+=("$chart")
  fi
done < <(echo -n "$changed")
```

(this releases new versions on closed PRs, so I guess this needs some changes in order to also run on pushes to `main` and other cases)

**Comment by pascaliske** [comment]
This would be an awesome addition for a workflow where the charts should be pushed to an OCI registry as well:

```yaml
# deploy charts to github pages
- uses: helm/chart-releaser-action@v1.7.0
  id: cr
  env:
    CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    CR_GENERATE_RELEASE_NOTES: true
    CR_SKIP_EXISTING: true

# setup access to container registry
- uses: docker/login-action@v3
  if: ${{ steps.cr.outputs.changed_charts }}
  with: # [...]

# push charts to container registry
- name: Push charts to container registry
  if: ${{ steps.cr.outputs.changed_charts }}
  run: |
    for CHART in .cr-release-packages/*; do
      if [ -z "${CHART:-}" ]; then break; fi
      helm push "${CHART}" oci://ghcr.io/${{ github.repository }}
    done
```
