### ISSUE TITLE
Is there any way to provide package-path `-p` from chart-releaser?

### ISSUE THREAD

**Issue by onkarganjewar** [helm/chart-releaser-action#25]
I'm following the examples shown in [helm/chart-releaser](https://github.com/helm/chart-releaser#environment-variables) and tried to upload a helm chart package path using
1. Env var: `CR_PACKAGE_PATH` 
2. Manually creating the directory `.cr-release-packages/`

But, my workflow job still exits with the message: `Nothing to do. No chart changes detected.`

Here's my workflow:
```
name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@master
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'
          # CR_PACKAGE_PATH: 'pkgs'
```

Is this behavior currently supported? I'm using the GitHub enterprise account, not sure if that makes any difference. Any help or suggestions much appreciated! Thanks!
