### ISSUE TITLE
error creating GitHub release: 404 Not found

### ISSUE THREAD

**Issue by schizoid90** [helm/chart-releaser-action#38]
Been banging my head against a wall with this one. I've created my workflow according to the example

```
name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
          charts_repo_url: "https://schizoid90.github.io/krew-museum"
          charts_dir: "./charts"
        env:
          CR_TOKEN: "${{ secrets.CR_PAT }}"
```

When it runs I get the error

```
Successfully packaged chart and saved it to: .cr-release-packages/krew-museum-0.1.1.tgz
Releasing charts...
Error: error creating GitHub release: POST https://api.github.com/repos/schizoid90/krew-museum/releases: 404 Not Found []
```

When I hit that page in my browser i don't get a 404 error so it does exist.

My directory layout is as below

```
.
├── Dockerfile
├── LICENSE
├── README.md
├── charts
│   └── krew-museum
│       ├── Chart.yaml
│       ├── templates
│       │   ├── _helpers.tpl
│       │   ├── deployment.yaml
│       │   ├── ingress.yaml
│       │   ├── service.yaml
│       │   └── statefulset.yaml
│       └── values.yaml
└── src
    ├── handlers.go
    ├── helpers.go
    └── main.go
```

anyone able to point me where I'm going wrong?

Many thanks
