### ISSUE TITLE
Error dealing with charts with dependencies

### ISSUE THREAD

**Issue by davidkarlsen** [helm/chart-releaser-action#6]
Look at https://github.com/evryfs/helm-charts/commit/7758626b628d9b2a86d06f56709e0f72450360d0/checks?check_suite_id=351179142 - it seems the releaser has problems dealing with charts that have dependencies, as it fails with:
```
Run helm/chart-releaser-action@v1.0.0-alpha.1
helm-charts
Looking up latest tag...
Discovering changed charts since 'c7a9c284c1570187a269698c01d1821ac775917c'...
Installing chart-releaser...
Packaging chart 'charts/mcrouter'...
Error: Couldn't load repositories file (/home/runner/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
##[error]Node run failed with exit code 1
```

**Comment by unguiculus** [comment]
Thanks for reporting. I'll look into it. From what I've seen, Helm needs to be installed in the first place. This is an oversight because initial testing of the set of actions happened in one workflow and Helm was already there in that case.

**Comment by unguiculus** [comment]
I looked into this. Installing Helm alone doesn't really solve this. We would also have to add chart repos for the dependencies. The question is whether this should be part of the chart-releaser action. It may be better to provide a separate action that installs Helm. That could be generally useful anyways. It probably would then look like this:

```yaml
name: release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: helm/helm-install-action@v1.0.0

      - name: Add Helm repos
        run: |
          helm repo add foo https://foo.helm.example.com
          helm repo add bar https://bar.helm.example.com

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.1
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"

```
