### ISSUE TITLE
Action removes untouched charts from index.yaml

### ISSUE THREAD

**Issue by ckotzbauer** [helm/chart-releaser-action#65]
Hi,

I found a weired behavior with this action. I use the following pipeline on a private repo. The action only writes those charts to the `index.yaml` file on the `gh-pages` branch which are updated in the current build. All charts which are untouched, are removed from the yaml and therefore cannot be installed anymore. The action log does not report those deletions (except the git-diff of deleted lines). Is there a solution for this?

```yaml
name: Release Charts

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
```
