### ISSUE TITLE
Documentation misleading?!

### ISSUE THREAD

**Issue by boxcee** [helm/chart-releaser-action#68]
Spent some time today fiddling around with your action.

I find the line
```
For more information on inputs, see the API Documentation
```
in the `README.md` a bit confusing.

For some reason I thought the `inputs` under the link could be used in a config file until I realized they are the options for the CLI.

Maybe the link can be removed? Or put in a different context?

**Comment by boxcee** [comment]
Instead maybe link the `cr` CLI documentation: https://github.com/helm/chart-releaser#configuration for the `config` input.

**Comment by Aisuko** [comment]
Yep, you are right. the `README.md` makes me a little confused.

**Comment by davidkarlsen** [comment]
> Instead maybe link the `cr` CLI documentation: https://github.com/helm/chart-releaser#configuration for the `config` input.

Do you want to provide a PR?

**Comment by boxcee** [comment]
@davidkarlsen sure! I completely removed the (for me) confusing line though. I think it is unrelated as it documentation regarding the GitHub API and has nothing to do with the `helm-chart-releaser` action.

**Comment by Aisuko** [comment]
I have a small suggestion, would you mind adding a demo to help the end-user to know how to add the parameters of release-actions.

Some like below, I believe that makes more sense.

```
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: charts
          config: cr.yaml
          charts_repo_url: https://meshery.io/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
