### ISSUE TITLE
No changes detected.

### ISSUE THREAD

**Issue by mhumeSF** [helm/chart-releaser-action#69]
Been having trouble getting this to work. I can't figure how to trigger this action to detect changes. I've commited changes under `charts/<chart-name>/Chart.yml` directly to `main` branch as well as make changes to the chart on another branch and merge. Either case yields "No changes deteced". The action, when looking for changes, looks to be performing the comparison against the latest commit and not a previous commit.

**Comment by ohdearaugustin** [comment]
if you use v1.1.0 checkout #61. I downgraded to version 1.0.0.

**Comment by mhumeSF** [comment]
This must confirm it's something with my workflow? I downgraded and still seeing the same behavior. 

```
Run helm/chart-releaser-action@v1.0.0
  with:
    charts_dir: charts
  env:
    CR_TOKEN: ***
helm-charts
Looking up latest tag...
Discovering changed charts since '2d7d1291bdc6b5a48fe1313d3115ea6e072a6916'...
Nothing to do. No chart changes detected.
```

This is my workflow file:
```
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
