### ISSUE TITLE
Feature: Support appending an existing release

### ISSUE THREAD

**Issue by callum-tait-pbx** [helm/chart-releaser-action#70]
**Problem**
If a release already exists with the same tag then chart-releaser fails with the following error:

```Error: error creating GitHub release: POST https://api.github.com/repos/my_org/actions-runner-controller-mirror/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]```

**Proposed Soltuion**
Check for a matching release beforehand and append to that release if the action is configured to do so. 

```yaml
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          APPEND_TO_RELEASE: true
```

To retain compatibility make the default value false.
