### ISSUE TITLE
No changes detected

### ISSUE THREAD

**Issue by hazcod** [helm/chart-releaser-action#71]
Hi, the action always returns `no changes detected`?

```yaml
on:
  push:
    branches: [master]


jobs:

  release-chart:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    -
      name: Install helm
      uses: azure/setup-helm@v1
    -
      name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.0.0
      env:
        CR_TOKEN: "${{ secrets.MY_TOKEN }}"

```

**Comment by smlx** [comment]
which git repo?

**Comment by hazcod** [comment]
@smlx it's a private repo, but I'm curious how it's supposed to detect changes.
Ideally I would like to tell it to release version X.

**Comment by g3rhard** [comment]
I saw the same error, when checkout step was not completely defined. Can you try to change checkout step to this:
```yaml
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important parameter
```

**Comment by nastra** [comment]
I am running into the same issue and it looks like this is being caused by this check here: https://github.com/helm/chart-releaser-action/blob/main/cr.sh#L57-L82

**Comment by seanmorton** [comment]
Using @g3rhard's advice to make sure `fetch-depth` is set fixed the problem for me.
```
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important parameter
```
