### ISSUE TITLE
Chart release failing with error `Error: no repository definition` for an existing repository

### ISSUE THREAD

**Issue by deshetti** [helm/chart-releaser-action#74]
I am adding a dependency to my chart to the following repository: https://k8s.ory.sh/helm/charts
The documentation for all the charts in this repo is mentioned here and works as expected: http://k8s.ory.sh/helm/
The helm chart repo works fine locally when I add it with the following command: `helm repo add ory https://k8s.ory.sh/helm/charts` and when I install the charts separately using Helm.

I am getting an error `Error: no repository definition for https://k8s.ory.sh/helm/charts` when I am adding one of the charts from the above repo as a dependency to my helm chart https://github.com/factly/helm-charts/blob/main/charts/kavach/Chart.yaml#L54

Here is the error in my Github Actions: https://github.com/factly/helm-charts/runs/1886221330?check_suite_focus=true

A couple of other chart dependencies I added work fine. Any charts within [this](https://k8s.ory.sh/helm/charts) repo are failing with the above error. Any help is greatly appreciated.

**Comment by Nuxij** [comment]
I also see this issue. I am trying to setup te action in this branch: https://github.com/Nuxij/charts

I receive `Error: no repository definition for https://charts.bitnami.com/bitnami`

I tried adding a "dependency" stage. This passes, but doesn't seem to effect the release stage:

```yml
- name: Helm Deps
  run: |
    for dir in $(ls -d charts/*); do
      helm dependency update $dir;
    done

- name: Run chart-releaser
  uses: helm/chart-releaser-action@v1.1.0
  env:
    CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
