### ISSUE TITLE
No changes detected is computed inside parent repository

### ISSUE THREAD

**Issue by testillano** [helm/chart-releaser-action#78]
Sorry for the strange title, but I will explain better.
I'm not sure if my procedure has sense and probably things could be done in better way:

Instead of having a _gh-pages_ branch in every of my account projects in order to publish their helm charts (indeed, your github action works like a charm, congrats), I though about a new setup in order to simplify my life (at least temporarily):

**What if I create my unique helm github project with helm publish workflow** (and of course, the GH Pages enabled on gh-pages branch) and such workflow just **checkout** the other projects within this one (for example under '**./cloned**' subdirectory), and then publish the charts within them (by mean _charts_dir_) once retrieved ?

Look at the workflow example below:
```yaml
name: Package helm charts and publish them into gh-pages branch
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on master branch
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: testillano/h1mock
          ref: refs/heads/master
          path: cloned/h1mock

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: cloned/h1mock/helm

```

Although I indicate the _charts_dir = cloned/h1mock/helm_ it seems that the helm releaser action compares the changes in the man repository. Indeed, I'm quite sure that even looking for the "repository" which corresponds to the provided _charts_dir_, probably there is no way to have a history for that. So, I think a good alternative would be to have an action parameter to **FORCE ANYWAY the helm release procedure**. Finally, the responsability is for the user who dispatch the workflow (if actually there are no changes, the helm packages would be overwritten with the same content, as a "lesser evil").

Could it be possible ? I have seen other issues asking for the same (i.e. https://github.com/helm/chart-releaser-action/issues/8).

thank u in advance !
