### ISSUE TITLE
Why do I have to nest my charts inside of the `charts/` subdirectory?

### ISSUE THREAD

**Issue by jon-whit** [helm/chart-releaser-action#87]
Lets say I have a Git repository structured like this:

```
github.com/myorg/helm-charts
    chart1/
        templates/
        Chart.yaml
    chart2/
        templates/
        Chart.yaml
    README.md
```

If I pass the `chart_dir` in my GitHub Workflow file as the current checked out working directory (e.g. `.`), it doesn't work. If I re-organize my repository structure so that it maps to:

```
github.com/myorg/helm-charts
    charts/
        chart1/
            templates/
            Chart.yaml
        chart2/
            templates/
            Chart.yaml
    README.md
```

it works just fine.

Having a top-level repository `helm-charts` and requiring a nested `charts` directory stutters and is completely unnecessary. Why was this design decision chosen and would you be willing to change it?

**Comment by torstenwalter** [comment]
Looks like the option is called `charts_dir` https://github.com/helm/chart-releaser-action/blob/c25b74a/action.yml#L25. So you've been missing the `s` at the end.

```
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: '.'
```

@jon-whit So I think this can be closed.
