### ISSUE TITLE
chart-releaser-action stops working after a precipitating failure

### ISSUE THREAD

**Issue by brian-pickens** [helm/chart-releaser-action#93]
## Description
I am running into a series of consistent errors on my self-hosted runner attempting to run the chart-releaser-action. What happens is that an initial run failure then seems to trigger the chart-releaser-action to stop working all together by not being able to run the ./cr.sh script any longer.

## First Failure
```bash
Run helm/chart-releaser-action@v1.2.1
Looking up latest tag...
Discovering changed charts since 'test-0.0.4'...
Installing chart-releaser...
Adding cr directory to PATH...
Packaging chart 'charts/test'...
Successfully packaged chart in /mnt/c/Users/chart-releaser/actions-runner/_work/helm-charts/helm-charts/charts/test and saved it to: .cr-release-packages/test-0.0.6.tgz
Releasing charts...
Updating charts repo index...
Using existing index at .cr-index/index.yaml
Error: error loading .cr-index/index.yaml: error converting YAML to JSON: yaml: line 184: mapping values are not allowed in this context
```

## Action stops working

After the first failure, every subsequent run concludes with `cr: command not found` until I stop the github actionrunner, reconfigure it, and then start it again.

```bash
Run helm/chart-releaser-action@v1.2.1
  with:
    charts_dir: charts
  env:
    CR_TOKEN: ***
Looking up latest tag...
Discovering changed charts since 'test-0.0.6'...
Packaging chart 'charts/test'...
/mnt/c/Users/chart-releaser/actions-runner/_work/_actions/helm/chart-releaser-action/v1.2.1/cr.sh: line 243: cr: command not found
Error: Process completed with exit code 127.
```

## Git Directory
![image](https://user-images.githubusercontent.com/3659859/128220683-a7f73185-53fd-4a51-a031-cfa929fe5e27.png)

## Simple Test Chart

```yaml
name: test
description: Testing the chart releaser
version: 0.0.7
apiVersion: v1
keywords:
  - test
sources:
home:
```

## Release Charts Workflow
```yaml
name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      -  "charts/**"

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

**Comment by brian-pickens** [comment]
For posterity, the fix for this was to include the cr.yaml file including the 'owner' and 'git-repo' fields. In addition I updated my workflow file with the following properties for the chart-releaser:

```yaml
        with:
          charts_dir: charts
          config: cr.yaml
          charts_repo_url: xxxx
```
