### ISSUE TITLE
feat: Add json output

### ISSUE THREAD

**Issue by stevehipwell** [helm/chart-releaser-action#95]
I'd like to be able drive further actions from the output of the chart releaser action. My suggested implementation would be to return json in the format `[{"chart": "my-chart", "version": "1.0.0", "tag": "my-chart-1.0.0"}].

This output could then be used to drive a matrix. See below for an example of updating the release notes with a CHANGELOG entry (for https://github.com/helm/chart-releaser-action/issues/44).

```yaml
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        id: release_step
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    
    outputs:
       versions: ${{ steps.release_step.outputs.releases }}

  changelog:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.release.outputs.versions) }}
    steps:
      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./charts/${{matrix.chart}}/CHANGELOG.md
          version: "v${{matrix.version}}"

      - name: Update release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: ${{ steps.changelog_reader.outputs.changes }}
          tag: ${{matrix.tag}}
          token: ${{ secrets.GITHUB_TOKEN }}
```
